# Generated by Django 6.0.5 on 2026-05-20 06:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 27, 6, 11, 40, 727018, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='issuebook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
