# Generated by Django 6.0.5 on 2026-05-20 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_issuebook_due_date_issuebook_fine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='return_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 27, 6, 29, 44, 195692, tzinfo=datetime.timezone.utc)),
        ),
    ]
