# Generated by Django 6.0.5 on 2026-05-21 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_issuebook_return_request_alter_issuebook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 28, 5, 46, 4, 582691, tzinfo=datetime.timezone.utc)),
        ),
    ]
