# Generated by Django 6.0.5 on 2026-05-22 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_issuebook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 29, 8, 40, 57, 879791, tzinfo=datetime.timezone.utc)),
        ),
    ]
