# Generated by Django 6.0.5 on 2026-05-26 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_issuebook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 2, 4, 51, 19, 750912, tzinfo=datetime.timezone.utc)),
        ),
    ]
